// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShipmentDeliveryAPI.Data;

#nullable disable

namespace ShipmentDeliveryAPI.Migrations
{
    [DbContext(typeof(ShipmentDeliveryContext))]
    [Migration("20250814032203_UpdatedModel")]
    partial class UpdatedModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.BulkItem", b =>
                {
                    b.Property<int>("BulkItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EvdSealNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("BulkItemId");

                    b.HasIndex("DeliveryId", "MaterialNumber", "EvdSealNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_BulkItem_Unique");

                    b.ToTable("BulkItems");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.ContainerItem", b =>
                {
                    b.Property<int>("ContainerItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MaterialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ContainerItemId");

                    b.HasIndex("DeliveryId", "MaterialNumber", "SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_ContainerItem_Unique");

                    b.ToTable("ContainerItems");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.Delivery", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DeliveryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DeliveryType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ShipmentId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("DeliveryId");

                    b.HasIndex("DeliveryNumber")
                        .IsUnique();

                    b.HasIndex("ShipmentId");

                    b.ToTable("Deliveries");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.Shipment", b =>
                {
                    b.Property<int>("ShipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ShipmentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("ShipmentId");

                    b.HasIndex("ShipmentNumber")
                        .IsUnique();

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.BulkItem", b =>
                {
                    b.HasOne("ShipmentDeliveryAPI.Models.Delivery", "Delivery")
                        .WithMany("BulkItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.ContainerItem", b =>
                {
                    b.HasOne("ShipmentDeliveryAPI.Models.Delivery", "Delivery")
                        .WithMany("ContainerItems")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.Delivery", b =>
                {
                    b.HasOne("ShipmentDeliveryAPI.Models.Shipment", "Shipment")
                        .WithMany("Deliveries")
                        .HasForeignKey("ShipmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Shipment");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.Delivery", b =>
                {
                    b.Navigation("BulkItems");

                    b.Navigation("ContainerItems");
                });

            modelBuilder.Entity("ShipmentDeliveryAPI.Models.Shipment", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
